import { ShieldAlert, Bell, Monitor, FlaskConical } from 'lucide-react'

const stats = [
  { label: 'Active Incidents', value: '0', color: '#e74c3c', icon: ShieldAlert },
  { label: 'Open Alerts', value: '0', color: '#f39c12', icon: Bell },
  { label: 'Devices Monitored', value: '0', color: '#0078d4', icon: Monitor },
  { label: 'Labs Available', value: '0', color: '#27ae60', icon: FlaskConical },
]

export default function Dashboard() {
  return (
    <div style={{ padding: '32px' }}>

      {/* Header */}
      <div style={{ marginBottom: '32px' }}>
        <h1 style={{ fontSize: '24px', fontWeight: 700, color: '#ffffff' }}>
          Microsoft SIEM & XDR Simulator
        </h1>
        <p style={{ color: '#8888aa', marginTop: '6px', fontSize: '14px' }}>
          Welcome to your security training environment. Select a module from the sidebar to get started.
        </p>
      </div>

      {/* Stats Cards */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
        gap: '16px',
        marginBottom: '32px',
      }}>
        {stats.map(({ label, value, color, icon: Icon }) => (
          <div key={label} style={{
            background: '#1a1a2e',
            border: '1px solid #2a2a4a',
            borderRadius: '8px',
            padding: '20px',
            display: 'flex',
            alignItems: 'center',
            gap: '16px',
          }}>
            <div style={{
              width: '44px',
              height: '44px',
              borderRadius: '8px',
              background: `${color}22`,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
            }}>
              <Icon size={22} color={color} />
            </div>
            <div>
              <div style={{ fontSize: '28px', fontWeight: 700, color: '#ffffff' }}>{value}</div>
              <div style={{ fontSize: '12px', color: '#8888aa' }}>{label}</div>
            </div>
          </div>
        ))}
      </div>

      {/* Getting Started */}
      <div style={{
        background: '#1a1a2e',
        border: '1px solid #2a2a4a',
        borderRadius: '8px',
        padding: '24px',
      }}>
        <h2 style={{ fontSize: '16px', fontWeight: 600, marginBottom: '16px', color: '#ffffff' }}>
          Getting Started
        </h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '12px' }}>
          {[
            { step: '1', title: 'Start a Scenario', desc: 'Go to Labs and launch an attack scenario to generate simulated alerts and incidents.' },
            { step: '2', title: 'Investigate Incidents', desc: 'Head to Incidents to triage and investigate the alerts generated by your scenario.' },
            { step: '3', title: 'Query with KQL', desc: 'Use the KQL Editor to write queries against the simulated log data.' },
            { step: '4', title: 'Complete Labs', desc: 'Follow guided labs to build skills and earn points on your way to certification readiness.' },
          ].map(({ step, title, desc }) => (
            <div key={step} style={{
              background: '#0f0f1a',
              border: '1px solid #2a2a4a',
              borderRadius: '6px',
              padding: '16px',
            }}>
              <div style={{
                width: '28px',
                height: '28px',
                borderRadius: '50%',
                background: '#0078d4',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '13px',
                fontWeight: 700,
                marginBottom: '10px',
              }}>{step}</div>
              <div style={{ fontSize: '13px', fontWeight: 600, marginBottom: '6px', color: '#ffffff' }}>{title}</div>
              <div style={{ fontSize: '12px', color: '#8888aa', lineHeight: '1.5' }}>{desc}</div>
            </div>
          ))}
        </div>
      </div>

    </div>
  )
}